# Generated by Django 4.0.2 on 2022-07-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_doapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='To_doo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
