# Generated by Django 4.0.2 on 2022-07-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_doapp', '0002_to_doo'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_doo',
            name='duedate',
            field=models.CharField(default='', max_length=50),
        ),
    ]
