# Generated by Django 4.0.2 on 2022-07-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_doapp', '0003_to_doo_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_doo',
            name='duedate',
            field=models.DateField(),
        ),
    ]
