# Generated by Django 4.0.2 on 2022-07-27 06:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_doapp', '0007_alter_login_email_alter_to_doo_duedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='to_doo',
            name='duedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 27, 12, 4, 40, 404465)),
        ),
        migrations.AddField(
            model_name='to_doo',
            name='todo_list',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='to_doapp.todolist'),
            preserve_default=False,
        ),
    ]
