# Generated by Django 4.0.2 on 2022-07-28 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_doapp', '0011_alter_to_doo_duedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='to_doo',
            name='todo_list',
        ),
        migrations.AlterField(
            model_name='to_doo',
            name='duedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 28, 17, 31, 36, 591420)),
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
